import { Holding } from './types';

export const INITIAL_HOLDINGS: Holding[] = [
  // Financial Sector
  {
    id: 'hold-1',
    symbol: 'HDFCBANK',
    name: 'HDFC Bank',
    sector: 'Financial Sector',
    purchasePrice: 1490,
    quantity: 50,
    yahooSymbol: 'HDFCBANK.NS',
    googleSymbol: 'HDFCBANK:NSE',
    cmp: 1700.15,
    peRatio: 18.69,
    eps: 91.02,
  },
  {
    id: 'hold-2',
    symbol: 'BAJFINANCE',
    name: 'Bajaj Finance',
    sector: 'Financial Sector',
    purchasePrice: 6466,
    quantity: 15,
    yahooSymbol: 'BAJFINANCE.NS',
    googleSymbol: 'BAJFINANCE:NSE',
    cmp: 8419.6,
    peRatio: 32.63,
    eps: 257.8,
  },
  {
    id: 'hold-3',
    symbol: '532174',
    name: 'ICICI Bank',
    sector: 'Financial Sector',
    purchasePrice: 780,
    quantity: 84,
    yahooSymbol: 'ICICIBANK.NS',
    googleSymbol: 'ICICIBANK:NSE',
    cmp: 1215.5,
    peRatio: 17.68,
    eps: 68.72,
  },
  {
    id: 'hold-4',
    symbol: '544252',
    name: 'Bajaj Housing',
    sector: 'Financial Sector',
    purchasePrice: 130,
    quantity: 504,
    yahooSymbol: 'BAJAJHFL.NS',
    googleSymbol: 'BAJAJHFL:NSE',
    cmp: 112.85,
    peRatio: 85.72,
    eps: 2.53,
  },
  {
    id: 'hold-5',
    symbol: '511577',
    name: 'Savani Financials',
    sector: 'Financial Sector',
    purchasePrice: 24,
    quantity: 1080,
    yahooSymbol: '511577.BO',
    googleSymbol: '511577:BOM',
    cmp: 14.86,
    peRatio: 'N/A',
    eps: 'N/A',
  },

  // Tech Sector
  {
    id: 'hold-6',
    symbol: 'AFFLE',
    name: 'Affle India',
    sector: 'Tech Sector',
    purchasePrice: 1151,
    quantity: 50,
    yahooSymbol: 'AFFLE.NS',
    googleSymbol: 'AFFLE:NSE',
    cmp: 1459.6,
    peRatio: 55.53,
    eps: 26.11,
  },
  {
    id: 'hold-7',
    symbol: 'LTIM',
    name: 'LTI Mindtree',
    sector: 'Tech Sector',
    purchasePrice: 4775,
    quantity: 16,
    yahooSymbol: 'LTIM.NS',
    googleSymbol: 'LTIM:NSE',
    cmp: 4793.8,
    peRatio: 34.69,
    eps: 145.92,
  },
  {
    id: 'hold-8',
    symbol: '542651',
    name: 'KPIT Tech',
    sector: 'Tech Sector',
    purchasePrice: 672,
    quantity: 61,
    yahooSymbol: 'KPITTECH.NS',
    googleSymbol: 'KPITTECH:NSE',
    cmp: 1293.1,
    peRatio: 46.57,
    eps: 27.77,
  },
  {
    id: 'hold-9',
    symbol: '544028',
    name: 'Tata Tech',
    sector: 'Tech Sector',
    purchasePrice: 1072,
    quantity: 63,
    yahooSymbol: 'TATATECH.NS',
    googleSymbol: 'TATATECH:NSE',
    cmp: 662.0,
    peRatio: 41.68,
    eps: 15.88,
  },
  {
    id: 'hold-10',
    symbol: '544107',
    name: 'BLS E-Services',
    sector: 'Tech Sector',
    purchasePrice: 232,
    quantity: 191,
    yahooSymbol: 'BLSE.NS',
    googleSymbol: 'BLSE:NSE',
    cmp: 152.9,
    peRatio: 26.3,
    eps: 5.8,
  },
  {
    id: 'hold-11',
    symbol: '532790',
    name: 'Tanla',
    sector: 'Tech Sector',
    purchasePrice: 1134,
    quantity: 45,
    yahooSymbol: 'TANLA.NS',
    googleSymbol: 'TANLA:NSE',
    cmp: 449.5,
    peRatio: 11.64,
    eps: 39.48,
  },

  // Consumer Sector
  {
    id: 'hold-12',
    symbol: 'DMART',
    name: 'Dmart',
    sector: 'Consumer Sector',
    purchasePrice: 3777,
    quantity: 27,
    yahooSymbol: 'DMART.NS',
    googleSymbol: 'DMART:NSE',
    cmp: 3451.1,
    peRatio: 82.63,
    eps: 41.75,
  },
  {
    id: 'hold-13',
    symbol: '532540',
    name: 'Tata Consumer',
    sector: 'Consumer Sector',
    purchasePrice: 845,
    quantity: 90,
    yahooSymbol: 'TATACONSUM.NS',
    googleSymbol: 'TATACONSUM:NSE',
    cmp: 961.1,
    peRatio: 26.56,
    eps: 134.77,
  },
  {
    id: 'hold-14',
    symbol: '500331',
    name: 'Pidilite',
    sector: 'Consumer Sector',
    purchasePrice: 2376,
    quantity: 36,
    yahooSymbol: 'PIDILITIND.NS',
    googleSymbol: 'PIDILITIND:NSE',
    cmp: 2730.0,
    peRatio: 71.13,
    eps: 38.36,
  },

  // Power Sector
  {
    id: 'hold-15',
    symbol: '500400',
    name: 'Tata Power',
    sector: 'Power Sector',
    purchasePrice: 224,
    quantity: 225,
    yahooSymbol: 'TATAPOWER.NS',
    googleSymbol: 'TATAPOWER:NSE',
    cmp: 351.0,
    peRatio: 29.36,
    eps: 11.94,
  },
  {
    id: 'hold-16',
    symbol: '542323',
    name: 'KPI Green',
    sector: 'Power Sector',
    purchasePrice: 875,
    quantity: 50,
    yahooSymbol: 'KPIGREEN.NS',
    googleSymbol: 'KPIGREEN:NSE',
    cmp: 402.4,
    peRatio: 29.26,
    eps: 13.75,
  },
  {
    id: 'hold-17',
    symbol: '532667',
    name: 'Suzlon',
    sector: 'Power Sector',
    purchasePrice: 44,
    quantity: 450,
    yahooSymbol: 'SUZLON.NS',
    googleSymbol: 'SUZLON:NSE',
    cmp: 51.36,
    peRatio: 61.25,
    eps: 0.84,
  },
  {
    id: 'hold-18',
    symbol: '542851',
    name: 'Gensol',
    sector: 'Power Sector',
    purchasePrice: 998,
    quantity: 45,
    yahooSymbol: 'GENSOL.NS',
    googleSymbol: 'GENSOL:NSE',
    cmp: 372.6,
    peRatio: 39.51,
    eps: 5.57,
  },

  // Pipe Sector
  {
    id: 'hold-19',
    symbol: '543517',
    name: 'Hariom Pipes',
    sector: 'Pipe Sector',
    purchasePrice: 580,
    quantity: 60,
    yahooSymbol: 'HARIOMPIPE.NS',
    googleSymbol: 'HARIOMPIPE:NSE',
    cmp: 355.75,
    peRatio: 17.98,
    eps: 19.78,
  },
  {
    id: 'hold-20',
    symbol: 'ASTRAL',
    name: 'Astral',
    sector: 'Pipe Sector',
    purchasePrice: 1517,
    quantity: 56,
    yahooSymbol: 'ASTRAL.NS',
    googleSymbol: 'ASTRAL:NSE',
    cmp: 1317.6,
    peRatio: 67.13,
    eps: 19.59,
  },
  {
    id: 'hold-21',
    symbol: '542652',
    name: 'Polycab',
    sector: 'Pipe Sector',
    purchasePrice: 2818,
    quantity: 28,
    yahooSymbol: 'POLYCAB.NS',
    googleSymbol: 'POLYCAB:NSE',
    cmp: 5000.0,
    peRatio: 40.91,
    eps: 121.97,
  },

  // Others
  {
    id: 'hold-22',
    symbol: '543318',
    name: 'Clean Science',
    sector: 'Others',
    purchasePrice: 1610,
    quantity: 32,
    yahooSymbol: 'CLEAN.NS',
    googleSymbol: 'CLEAN:NSE',
    cmp: 1237.45,
    peRatio: 50.37,
    eps: 24.52,
  },
  {
    id: 'hold-23',
    symbol: '506401',
    name: 'Deepak Nitrite',
    sector: 'Others',
    purchasePrice: 2248,
    quantity: 27,
    yahooSymbol: 'DEEPAKNTR.NS',
    googleSymbol: 'DEEPAKNTR:NSE',
    cmp: 1927.9,
    peRatio: 41.86,
    eps: 37.26,
  },
  {
    id: 'hold-24',
    symbol: '541557',
    name: 'Fine Organic',
    sector: 'Others',
    purchasePrice: 4284,
    quantity: 16,
    yahooSymbol: 'FINEORG.NS',
    googleSymbol: 'FINEORG:NSE',
    cmp: 3743.0,
    peRatio: 41.86,
    eps: 37.26,
  },
  {
    id: 'hold-25',
    symbol: '533282',
    name: 'Gravita',
    sector: 'Others',
    purchasePrice: 2037,
    quantity: 8,
    yahooSymbol: 'GRAVITA.NS',
    googleSymbol: 'GRAVITA:NSE',
    cmp: 1614.2,
    peRatio: 41.86,
    eps: 37.26,
  },
  {
    id: 'hold-26',
    symbol: '540719',
    name: 'SBI Life',
    sector: 'Others',
    purchasePrice: 1197,
    quantity: 49,
    yahooSymbol: 'SBILIFE.NS',
    googleSymbol: 'SBILIFE:NSE',
    cmp: 1405.45,
    peRatio: 'N/A',
    eps: -5.82,
  },

  // Additional Holdings from Sheet
  {
    id: 'hold-27',
    symbol: '500209',
    name: 'Infy',
    sector: 'Tech Sector',
    purchasePrice: 1647,
    quantity: 36,
    yahooSymbol: 'INFY.NS',
    googleSymbol: 'INFY:NSE',
    cmp: 1725.3,
    peRatio: 25.86,
    eps: 66.63,
  },
  {
    id: 'hold-28',
    symbol: '543237',
    name: 'Happiest Mind',
    sector: 'Tech Sector',
    purchasePrice: 1103,
    quantity: 45,
    yahooSymbol: 'HAPPSTMNDS.NS',
    googleSymbol: 'HAPPSTMNDS:NSE',
    cmp: 701.65,
    peRatio: 47.41,
    eps: 14.8,
  },
  {
    id: 'hold-29',
    symbol: '543272',
    name: 'Easemytrip',
    sector: 'Others',
    purchasePrice: 20,
    quantity: 1332,
    yahooSymbol: 'EASEMYTRIP.NS',
    googleSymbol: 'EASEMYTRIP:NSE',
    cmp: 11.51,
    peRatio: 41.86,
    eps: 37.26,
  },
];
